config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products,            only: [:show]
    resources :categories,          only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxonomies = Spree::Taxonomy.includes(:root)
    @taxon = Spree::Taxon.find(params[:id])
    @products = @taxon.all_products.includes(master: [:images, :default_price])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "BIGBAG Store".freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} - #{BASE_TITLE}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= DateTime.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-01-b11e080ea82bae88b23c85f7404765276aa5b481ab0079048429c92260e081f6.png" />
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-02-0712c5324717dda12ea95b7b634f5bcd0eaf91a9344c44e3fcc38d24c119c518.png" />
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-03-4b20bf7b56c22b46ec455c79a459f59f1993cc29bb57cc14d797c7b0a8e7aa13.png" />
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-04-e1435e6cf219d7f8999bc20ec12f116f1bd81dd25d8aafc450fb113fe1834df5.png" />
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-05-b541b14e4b66e08af1f0b005b0d8963c1fc1ae5772143df7f8acfd17635840ea.png" />
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-01-b11e080ea82bae88b23c85f7404765276aa5b481ab0079048429c92260e081f6.png" />
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-02-0712c5324717dda12ea95b7b634f5bcd0eaf91a9344c44e3fcc38d24c119c518.png" />
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <img alt="partner-img" src="/assets/home/partners/partner-03-4b20bf7b56c22b46ec455c79a459f59f1993cc29bb57cc14d797c7b0a8e7aa13.png" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_head.html.erb
<head>
  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>

  <!-- PLUGINS CSS STYLE -->

  <!-- GOOGLE FONT -->
  <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

  <!-- CUSTOM CSS -->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <form  id="form01" action="product-grid-left-sidebar.html" method="post">
                  <li>
                    <span class="input-group">
                      <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                      <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                    </span>
                  </li>
                </form>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to(image_tag("img/logo.png", :alt => "logo"), potepan_index_path, class: "navbar-brand") %>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active">
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li class="dropdown megaDropMenu">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer_light_section' %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_filter_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_filter_normal.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li>
    </ul>
  </div>
</div>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <%= link_to potepan_product_path(product.id) do %>
      <div class="productImage clearfix">
        <%= image_tag (product.display_image.attachment.url) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_product_categories.html.erb
<div class="panel-heading">商品カテゴリー</div>
<div class="panel-body">
  <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
    <% taxonomies.each do |taxonomy| %>
      <ul class="nav navbar-nav side-nav">
        <li>
          <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy-<%= taxonomy.id %>">
            <%= taxonomy.name %><i class="fa fa-plus"></i>
          </a>
          <ul id="taxonomy-<%= taxonomy.id %>" class="collapse collapseItem">
            <% taxonomy.root.leaves.each do |taxon| %>
              <li>
                <%= link_to potepan_category_path(taxon.id) do %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i>
                  <%= taxon.name %><span><%= "(#{taxon.products.count})" %></span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'layouts/light_section' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <%= render 'product_categories', { taxonomies: @taxonomies } %> 
        </div>
        <%= render 'filter_normal' %> 
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
      <%= render 'filter_area' %> 
        <div class="row">
          <%= render partial: 'product', collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<%= render 'layouts/light_section' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="col-xs-12">
      <div class="row singleProduct">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, i| %>
                  <div class="item <%= 'active' if i.zero? %>" data-thumb="<%= i %>">
                    <%= image_tag image.attachment(:large) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% @product.images.each_with_index do |image, i| %>
                    <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                      <%= image_tag image.attachment(:mini) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
              </a>
            </div>
          </div> 
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/blog_single_left_sidebar.html.erb
<% provide(:title, blog_single_left_sidebar) %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix blogPage singleBlog">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4 col-xs-12">
        <div class="row">
          <div class="col-xs-12">
            <div class="thumbnail">
              <%= image_tag("img/blog/blog-01.jpg", :alt => "blog-image") %>
              <div class="caption">
                <div class="row">
                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <h3>記事タイトル </h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>

                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
                  </div>
                </div>
              </div>
              <ul class="pager">
                <li class="previous"><a href="#">前の記事へ</a></li>
                <li class="next"><a href="#">次の記事へ</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8 col-xs-12 sideBar">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" aria-describedby="basic-addon2">
          <a href="#" class="input-group-addon" id="basic-addon2"><i class="fa fa-search"></i></a>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">カテゴリー</div>
          <div class="panel-body">
            <ul class="list-unstyle sidebar-list">
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>アクセサリー <span>(6)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>バッグ <span>(6)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>洋服 <span>(25)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>ベッド &amp; バス <span>(2)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スイミング <span>(5)</span></a></li>
              <li><a href="#"><i class="fa fa-caret-right" aria-hidden="true"></i>スポーツウェア &amp; シューズ <span>(3)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default recentBlogPosts">
          <div class="panel-heading">最新記事</div>
          <div class="panel-body">
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-01.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-02.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
            <div class="media">
              <a class="media-left" href="blog_single_right_sidebar.html">
                <%= image_tag("img/blog/blog-small-03.jpg", :class => "media-object", :alt => "Image") %>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><a href="blog_single_right_sidebar.html">記事タイトル（20文字）</a></h4>
                <p><i class="fa fa-calendar" aria-hidden="true"></i>2016/5/5</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<% provide(:title, checkout_complete) %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>